parameters:
#    harvest_cloud_messenger.example.class: HarvestCloud\MessengerBundle\Example

services:
#    harvest_cloud_messenger.example:
#        class: %harvest_cloud_messenger.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
