parameters:
    harvest_cloud_notifier.notifier.class: HarvestCloud\NotifierBundle\Notifier

services:
    notifier:
        class: %harvest_cloud_notifier.notifier.class%
        arguments: [@mailer, @templating]
